<?php

use Drupal\Core\Template\Attribute;
use Drupal\node\Entity\Node;


function pagebuilder_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  //kint($suggestions);
  if(in_array("field__block_content__field_columns__landingpage_row", $suggestions)) {
    $suggestions[] = 'pagebuilder__landingpage_row';
  }
  if(in_array("field__node__field_row__landingpage", $suggestions)) {
    $suggestions[] = 'pagebuilder__landingpage';
  }
}

function pagebuilder_preprocess_page(&$variables) {
  if (($node = \Drupal::routeMatch()->getParameter('node')) && $node instanceof \Drupal\node\NodeInterface) {
    if($node->getType() == 'landingpage'){
      $variables['#attached']['library'][] = 'pagebuilder/base-style';
    }
  }
}
/**
 * Implements hook_theme().
 */
function pagebuilder_theme() {
  return array(
    'pagebuilder__landingpage_row' => array(
      'preprocess functions' => array(
        'template_preprocess_field',
        )
    ),
    'pagebuilder__landingpage' => array(
      'preprocess functions' => array(
        'template_preprocess_field',
        )
    ),
  );
}


